name: astrocut

channels:
    - astropy

dependencies:
    - python=3.6
    - astropy
    - sphinx-astropy
    - Cython
    - matplotlib
    - numpy
    - configparser
#   - pip:
#       - dependency_from_pip
